import "dotenv/config";
import { PrismaClient, ImportStatus, LeadStatus, PotentialLevel, UserRole } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const adminPassword = await bcrypt.hash("admin123", 10);
  const salesPassword = await bcrypt.hash("deusa123", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@deusa.com.br" },
    update: {},
    create: {
      name: "Administrador Deusa",
      email: "admin@deusa.com.br",
      passwordHash: adminPassword,
      role: UserRole.ADMIN,
    },
  });

  const rafael = await prisma.user.upsert({
    where: { email: "rafael.mendes@deusa.com.br" },
    update: {},
    create: {
      name: "Rafael Mendes",
      email: "rafael.mendes@deusa.com.br",
      passwordHash: salesPassword,
      role: UserRole.SALES,
    },
  });

  const mariana = await prisma.user.upsert({
    where: { email: "mariana.alves@deusa.com.br" },
    update: {},
    create: {
      name: "Mariana Alves",
      email: "mariana.alves@deusa.com.br",
      passwordHash: salesPassword,
      role: UserRole.MANAGER,
    },
  });

  const camila = await prisma.user.upsert({
    where: { email: "camila.rocha@deusa.com.br" },
    update: {},
    create: {
      name: "Camila Rocha",
      email: "camila.rocha@deusa.com.br",
      passwordHash: salesPassword,
      role: UserRole.SALES,
    },
  });

  const felipe = await prisma.user.upsert({
    where: { email: "felipe.lima@deusa.com.br" },
    update: {},
    create: {
      name: "Felipe Lima",
      email: "felipe.lima@deusa.com.br",
      passwordHash: salesPassword,
      role: UserRole.SALES,
    },
  });

  const citySeed = [
    ["Tupã", "SP", "3555000"],
    ["Marília", "SP", "3529005"],
    ["Pompeia", "SP", "3540002"],
    ["Garça", "SP", "3516705"],
    ["Bastos", "SP", "3505807"],
    ["Assis", "SP", "3504008"],
    ["Ourinhos", "SP", "3534708"],
    ["Lins", "SP", "3527108"],
    ["Bauru", "SP", "3506003"],
    ["Presidente Prudente", "SP", "3541406"],
    ["Araçatuba", "SP", "3502804"],
  ] as const;

  for (const [name, uf, ibgeCode] of citySeed) {
    await prisma.city.upsert({
      where: { name_uf: { name, uf } },
      update: { ibgeCode, isActive: true },
      create: { name, uf, ibgeCode, isActive: true },
    });
  }

  const cnaes = [
    { code: "4711302", description: "Supermercados", category: "Varejo alimentar", isTarget: true },
    { code: "4712100", description: "Minimercados, mercearias e armazéns", category: "Varejo alimentar", isTarget: true },
    { code: "4721102", description: "Padarias e confeitarias com predominância de revenda", category: "Varejo alimentar", isTarget: true },
    { code: "4729699", description: "Comércio varejista de produtos alimentícios em geral", category: "Varejo alimentar", isTarget: true },
    { code: "4639701", description: "Comércio atacadista de produtos alimentícios em geral", category: "Atacado alimentar", isTarget: true },
    { code: "5611203", description: "Lanchonetes, casas de chá, de sucos e similares", category: "Food service", isTarget: false },
  ];

  for (const cnae of cnaes) {
    await prisma.cnae.upsert({
      where: { code: cnae.code },
      update: cnae,
      create: cnae,
    });
  }

  const companies = [
    {
      cnpj: "12345678000190",
      razaoSocial: "Mercadinho Sao Jose de Tupa Ltda",
      nomeFantasia: "Mercadinho São José",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2018-04-12"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Tupã",
      bairro: "Centro",
      cep: "17600010",
      logradouro: "Rua Caingangs",
      numero: "430",
      latitude: -21.9347,
      longitude: -50.5136,
      source: "seed",
      score: 90,
      status: LeadStatus.NEW,
      potentialLevel: PotentialLevel.CRITICAL,
      assignedToId: rafael.id,
      notes: "Alta aderência ao mix de varejo alimentar. Priorizar oferta de giro rápido.",
      lastContactAt: null,
      nextActionAt: new Date("2026-06-26T13:00:00-03:00"),
      interactions: [],
    },
    {
      cnpj: "23456789000167",
      razaoSocial: "Supermercado Avenida Marilia Ltda",
      nomeFantasia: "Supermercado Avenida",
      situacaoCadastral: "ATIVA",
      porte: "EPP",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2012-09-03"),
      cnaePrincipal: "4711302",
      uf: "SP",
      cidade: "Marília",
      bairro: "Jardim Maria Izabel",
      cep: "17515000",
      logradouro: "Avenida Sampaio Vidal",
      numero: "1850",
      latitude: -22.2171,
      longitude: -49.9501,
      source: "seed",
      score: 89,
      status: LeadStatus.CONTACTED,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: mariana.id,
      notes: "Comprador pediu tabela de preços para linha de empanados e frios.",
      lastContactAt: new Date("2026-06-20T10:30:00-03:00"),
      nextActionAt: new Date("2026-06-27T09:00:00-03:00"),
      interactions: [
        {
          userId: mariana.id,
          type: "Contato comercial",
          description: "Ligação com o setor de compras. Solicitou apresentação da tabela semanal.",
          createdAt: new Date("2026-06-20T10:30:00-03:00"),
        },
      ],
    },
    {
      cnpj: "11222333000144",
      razaoSocial: "Emporio Familia Pompeia Ltda",
      nomeFantasia: "Empório Família",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2020-01-20"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Pompeia",
      bairro: "Centro",
      cep: "17580000",
      logradouro: "Rua Getulio Vargas",
      numero: "112",
      latitude: -22.107,
      longitude: -50.1712,
      source: "seed",
      score: 88,
      status: LeadStatus.INTERESTED,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: camila.id,
      notes: "Interesse em abastecimento recorrente para balcão de frios.",
      lastContactAt: new Date("2026-06-19T15:45:00-03:00"),
      nextActionAt: new Date("2026-06-25T11:00:00-03:00"),
      interactions: [
        {
          userId: camila.id,
          type: "WhatsApp",
          description: "Cliente confirmou interesse e pediu condições para primeira compra.",
          createdAt: new Date("2026-06-19T15:45:00-03:00"),
        },
      ],
    },
    {
      cnpj: "45678901000123",
      razaoSocial: "Mercado Uniao Garca Ltda",
      nomeFantasia: "Mercado União",
      situacaoCadastral: "ATIVA",
      porte: "EPP",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2016-07-18"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Garça",
      bairro: "Williams",
      cep: "17400000",
      logradouro: "Rua Carlos Ferrari",
      numero: "760",
      latitude: -22.2125,
      longitude: -49.6546,
      source: "seed",
      score: 84,
      status: LeadStatus.NEGOTIATION,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: rafael.id,
      notes: "Negociando volume mínimo e entrega semanal às terças-feiras.",
      lastContactAt: new Date("2026-06-18T14:20:00-03:00"),
      nextActionAt: new Date("2026-06-24T16:30:00-03:00"),
      interactions: [
        {
          userId: rafael.id,
          type: "Proposta",
          description: "Enviada proposta com combo inicial para linha de varejo alimentar.",
          createdAt: new Date("2026-06-18T14:20:00-03:00"),
        },
        {
          userId: mariana.id,
          type: "Follow-up",
          description: "Validação interna de margem antes do fechamento.",
          createdAt: new Date("2026-06-21T09:10:00-03:00"),
        },
      ],
    },
    {
      cnpj: "78901234000156",
      razaoSocial: "Mini Mercado Central Bastos Ltda",
      nomeFantasia: "Mini Mercado Central",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2019-05-11"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Bastos",
      bairro: "Centro",
      cep: "17690000",
      logradouro: "Rua Presidente Vargas",
      numero: "95",
      latitude: -21.921,
      longitude: -50.7358,
      source: "seed",
      score: 72,
      status: LeadStatus.CONVERTED,
      potentialLevel: PotentialLevel.MEDIUM,
      assignedToId: felipe.id,
      notes: "Cliente convertido com pedido piloto quinzenal.",
      lastContactAt: new Date("2026-06-17T08:50:00-03:00"),
      nextActionAt: new Date("2026-07-01T10:00:00-03:00"),
      interactions: [
        {
          userId: felipe.id,
          type: "Pedido",
          description: "Primeiro pedido registrado para abastecimento de balcão refrigerado.",
          createdAt: new Date("2026-06-17T08:50:00-03:00"),
        },
      ],
    },
    {
      cnpj: "50987654000188",
      razaoSocial: "Padaria Aurora de Assis Ltda",
      nomeFantasia: "Padaria Aurora",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2017-08-09"),
      cnaePrincipal: "4721102",
      uf: "SP",
      cidade: "Assis",
      bairro: "Vila Claudia",
      cep: "19800040",
      logradouro: "Avenida Rui Barbosa",
      numero: "1220",
      latitude: -22.6612,
      longitude: -50.4113,
      source: "mock-seed",
      score: 94,
      status: LeadStatus.CONTACTED,
      potentialLevel: PotentialLevel.CRITICAL,
      assignedToId: camila.id,
      notes: "Padaria com alto fluxo no almoço. Boa entrada para linha food service.",
      lastContactAt: new Date("2026-06-22T09:30:00-03:00"),
      nextActionAt: new Date("2026-06-25T09:30:00-03:00"),
      interactions: [
        {
          userId: camila.id,
          type: "Contato comercial",
          description: "Responsável pediu amostras e catálogo de produtos para balcão quente.",
          createdAt: new Date("2026-06-22T09:30:00-03:00"),
        },
      ],
    },
    {
      cnpj: "60987654000177",
      razaoSocial: "Atacarejo Novo Oeste Ltda",
      nomeFantasia: "Atacarejo Novo Oeste",
      situacaoCadastral: "ATIVA",
      porte: "DEMAIS",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2014-03-27"),
      cnaePrincipal: "4639701",
      uf: "SP",
      cidade: "Presidente Prudente",
      bairro: "Jardim Paulista",
      cep: "19023010",
      logradouro: "Avenida Washington Luiz",
      numero: "2840",
      latitude: -22.1211,
      longitude: -51.3881,
      source: "mock-seed",
      score: 93,
      status: LeadStatus.NEW,
      potentialLevel: PotentialLevel.CRITICAL,
      assignedToId: mariana.id,
      notes: "Potencial alto por porte e atuação atacadista. Primeiro contato ainda pendente.",
      lastContactAt: null,
      nextActionAt: new Date("2026-06-24T15:00:00-03:00"),
      interactions: [],
    },
    {
      cnpj: "71987654000166",
      razaoSocial: "Mercado Pioneiro Ourinhos Ltda",
      nomeFantasia: "Mercado Pioneiro",
      situacaoCadastral: "ATIVA",
      porte: "EPP",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2015-11-15"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Ourinhos",
      bairro: "Centro",
      cep: "19900031",
      logradouro: "Rua Paraná",
      numero: "610",
      latitude: -22.9787,
      longitude: -49.8701,
      source: "mock-seed",
      score: 87,
      status: LeadStatus.INTERESTED,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: felipe.id,
      notes: "Busca fornecedor regional para reduzir ruptura em finais de semana.",
      lastContactAt: new Date("2026-06-16T11:15:00-03:00"),
      nextActionAt: new Date("2026-06-25T14:30:00-03:00"),
      interactions: [
        {
          userId: felipe.id,
          type: "Reunião",
          description: "Apresentado portfólio e levantado volume médio mensal por categoria.",
          createdAt: new Date("2026-06-16T11:15:00-03:00"),
        },
      ],
    },
    {
      cnpj: "82987654000155",
      razaoSocial: "Super Lins Comercio de Alimentos Ltda",
      nomeFantasia: "Super Lins",
      situacaoCadastral: "ATIVA",
      porte: "EPP",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2011-06-02"),
      cnaePrincipal: "4711302",
      uf: "SP",
      cidade: "Lins",
      bairro: "Jardim Aeroporto",
      cep: "16400070",
      logradouro: "Rua Voluntário Vitoriano Borges",
      numero: "880",
      latitude: -21.6738,
      longitude: -49.7487,
      source: "mock-seed",
      score: 86,
      status: LeadStatus.NEGOTIATION,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: rafael.id,
      notes: "Negociação avançada para abastecimento inicial de duas lojas.",
      lastContactAt: new Date("2026-06-21T16:05:00-03:00"),
      nextActionAt: new Date("2026-06-26T10:20:00-03:00"),
      interactions: [
        {
          userId: rafael.id,
          type: "Proposta",
          description: "Proposta revisada com prazo de pagamento e logística compartilhada.",
          createdAt: new Date("2026-06-21T16:05:00-03:00"),
        },
      ],
    },
    {
      cnpj: "93987654000144",
      razaoSocial: "Casa de Carnes e Mercearia Bela Vista Ltda",
      nomeFantasia: "Mercearia Bela Vista",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2021-02-10"),
      cnaePrincipal: "4729699",
      uf: "SP",
      cidade: "Bauru",
      bairro: "Vila Cardia",
      cep: "17013110",
      logradouro: "Rua Gustavo Maciel",
      numero: "1522",
      latitude: -22.3231,
      longitude: -49.0738,
      source: "mock-seed",
      score: 81,
      status: LeadStatus.CONTACTED,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: camila.id,
      notes: "Perfil pequeno, mas com boa aderência a compras semanais.",
      lastContactAt: new Date("2026-06-14T10:00:00-03:00"),
      nextActionAt: new Date("2026-06-28T10:00:00-03:00"),
      interactions: [
        {
          userId: camila.id,
          type: "Contato comercial",
          description: "Proprietário pediu retorno após fechamento do inventário semanal.",
          createdAt: new Date("2026-06-14T10:00:00-03:00"),
        },
      ],
    },
    {
      cnpj: "04987654000133",
      razaoSocial: "Emporio Noroeste Aracatuba Ltda",
      nomeFantasia: "Empório Noroeste",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2019-12-04"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Araçatuba",
      bairro: "São Joaquim",
      cep: "16050040",
      logradouro: "Rua do Fico",
      numero: "410",
      latitude: -21.2059,
      longitude: -50.4389,
      source: "mock-seed",
      score: 79,
      status: LeadStatus.NEW,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: felipe.id,
      notes: "Cadastro novo vindo de prospecção regional.",
      lastContactAt: null,
      nextActionAt: new Date("2026-06-27T13:30:00-03:00"),
      interactions: [],
    },
    {
      cnpj: "15987654000122",
      razaoSocial: "Mercado Vila Nova de Marilia Ltda",
      nomeFantasia: "Mercado Vila Nova",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2016-10-19"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Marília",
      bairro: "Vila Nova",
      cep: "17500080",
      logradouro: "Rua Nove de Julho",
      numero: "940",
      latitude: -22.2179,
      longitude: -49.9432,
      source: "mock-seed",
      score: 76,
      status: LeadStatus.NO_CONTACT,
      potentialLevel: PotentialLevel.HIGH,
      assignedToId: rafael.id,
      notes: "Lead aguardando primeira abordagem após enriquecimento cadastral.",
      lastContactAt: null,
      nextActionAt: new Date("2026-06-25T16:00:00-03:00"),
      interactions: [],
    },
    {
      cnpj: "26987654000111",
      razaoSocial: "Quitanda e Mercearia Primavera Ltda",
      nomeFantasia: "Mercearia Primavera",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2022-04-25"),
      cnaePrincipal: "4729699",
      uf: "SP",
      cidade: "Tupã",
      bairro: "Jardim América",
      cep: "17605020",
      logradouro: "Rua Aimorés",
      numero: "731",
      latitude: -21.9275,
      longitude: -50.5098,
      source: "mock-seed",
      score: 68,
      status: LeadStatus.INTERESTED,
      potentialLevel: PotentialLevel.MEDIUM,
      assignedToId: camila.id,
      notes: "Interessado em mix enxuto para teste de giro.",
      lastContactAt: new Date("2026-06-13T09:40:00-03:00"),
      nextActionAt: new Date("2026-06-30T09:40:00-03:00"),
      interactions: [
        {
          userId: camila.id,
          type: "WhatsApp",
          description: "Enviado catálogo compacto com sugestão de compra inicial.",
          createdAt: new Date("2026-06-13T09:40:00-03:00"),
        },
      ],
    },
    {
      cnpj: "37987654000100",
      razaoSocial: "Mini Mercado Estacao Pompeia Ltda",
      nomeFantasia: "Mini Mercado Estação",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2018-01-08"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Pompeia",
      bairro: "Flândria",
      cep: "17580060",
      logradouro: "Avenida Brasil",
      numero: "330",
      latitude: -22.1062,
      longitude: -50.1761,
      source: "mock-seed",
      score: 61,
      status: LeadStatus.NOT_INTERESTED,
      potentialLevel: PotentialLevel.MEDIUM,
      assignedToId: felipe.id,
      notes: "Sem interesse no momento por contrato vigente com outro fornecedor.",
      lastContactAt: new Date("2026-06-10T14:00:00-03:00"),
      nextActionAt: null,
      interactions: [
        {
          userId: felipe.id,
          type: "Descartado",
          description: "Responsável pediu novo contato apenas no próximo trimestre.",
          createdAt: new Date("2026-06-10T14:00:00-03:00"),
        },
      ],
    },
    {
      cnpj: "48987654000199",
      razaoSocial: "Mercado Popular Garca Ltda",
      nomeFantasia: "Mercado Popular",
      situacaoCadastral: "ATIVA",
      porte: "ME",
      matrizFilial: "MATRIZ",
      dataAbertura: new Date("2013-09-30"),
      cnaePrincipal: "4712100",
      uf: "SP",
      cidade: "Garça",
      bairro: "Labienópolis",
      cep: "17402080",
      logradouro: "Rua Barão do Rio Branco",
      numero: "1185",
      latitude: -22.2156,
      longitude: -49.6567,
      source: "mock-seed",
      score: 48,
      status: LeadStatus.INACTIVE,
      potentialLevel: PotentialLevel.LOW,
      assignedToId: rafael.id,
      notes: "Cadastro mantido para histórico; operação aparenta estar inativa.",
      lastContactAt: new Date("2026-05-28T11:20:00-03:00"),
      nextActionAt: null,
      interactions: [
        {
          userId: rafael.id,
          type: "Validação cadastral",
          description: "Telefone sem resposta e fachada fechada em visita externa.",
          createdAt: new Date("2026-05-28T11:20:00-03:00"),
        },
      ],
    },
  ];

  for (const item of companies) {
    const { score, status, potentialLevel, assignedToId, notes, lastContactAt, nextActionAt, interactions, ...companyData } = item;
    const company = await prisma.company.upsert({
      where: { cnpj: companyData.cnpj },
      update: {
        ...companyData,
        lastSyncAt: new Date(),
        cnaes: {
          deleteMany: {},
          create: [{ cnaeCode: companyData.cnaePrincipal, isPrimary: true }],
        },
      },
      create: {
        ...companyData,
        lastSyncAt: new Date(),
        cnaes: {
          create: [{ cnaeCode: companyData.cnaePrincipal, isPrimary: true }],
        },
      },
    });

    const lead = await prisma.lead.upsert({
      where: { companyId: company.id },
      update: {
        status,
        score,
        potentialLevel,
        assignedToId,
        notes,
        lastContactAt,
        nextActionAt,
      },
      create: {
        companyId: company.id,
        status,
        score,
        potentialLevel,
        assignedToId,
        notes,
        lastContactAt,
        nextActionAt,
      },
    });

    await prisma.leadInteraction.deleteMany({ where: { leadId: lead.id } });
    if (interactions.length > 0) {
      await prisma.leadInteraction.createMany({
        data: interactions.map((interaction) => ({
          leadId: lead.id,
          ...interaction,
        })),
      });
    }
  }

  await prisma.importJob.deleteMany({ where: { uf: "SP", cnaeCode: { in: ["4712100", "4711302", "4721102", "4639701"] } } });

  await prisma.importJob.create({
    data: {
      uf: "SP",
      cityName: "Tupã",
      cityIbgeCode: "3555000",
      cnaeCode: "4712100",
      status: ImportStatus.SUCCESS,
      totalFound: 1,
      totalSaved: 1,
      startedAt: new Date(),
      finishedAt: new Date(),
    },
  });

  await prisma.importJob.createMany({
    data: [
      {
        uf: "SP",
        cityName: "Marília",
        cityIbgeCode: "3529005",
        cnaeCode: "4711302",
        status: ImportStatus.SUCCESS,
        totalFound: 4,
        totalSaved: 4,
        startedAt: new Date("2026-06-20T08:00:00-03:00"),
        finishedAt: new Date("2026-06-20T08:02:00-03:00"),
      },
      {
        uf: "SP",
        cityName: "Assis",
        cityIbgeCode: "3504008",
        cnaeCode: "4721102",
        status: ImportStatus.SUCCESS,
        totalFound: 2,
        totalSaved: 2,
        startedAt: new Date("2026-06-22T08:00:00-03:00"),
        finishedAt: new Date("2026-06-22T08:01:00-03:00"),
      },
      {
        uf: "SP",
        cityName: "Presidente Prudente",
        cityIbgeCode: "3541406",
        cnaeCode: "4639701",
        status: ImportStatus.RUNNING,
        totalFound: 12,
        totalSaved: 8,
        startedAt: new Date("2026-06-24T08:30:00-03:00"),
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
