/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginResetPasswordRouteImport } from './routes/login.reset-password'
import { Route as AppRotasInteligentesRouteImport } from './routes/_app/rotas-inteligentes'
import { Route as AppRegioesPrioritariasRouteImport } from './routes/_app/regioes-prioritarias'
import { Route as AppRecomendacoesRouteImport } from './routes/_app/recomendacoes'
import { Route as AppMapaOportunidadesRouteImport } from './routes/_app/mapa-oportunidades'
import { Route as AppMapaDeCalorRouteImport } from './routes/_app/mapa-de-calor'
import { Route as AppLeadsB2bRouteImport } from './routes/_app/leads-b2b'
import { Route as AppImportarCnpjsRouteImport } from './routes/_app/importar-cnpjs'
import { Route as AppFunilComercialRouteImport } from './routes/_app/funil-comercial'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppBaseDeDadosRouteImport } from './routes/_app/base-de-dados'
import { Route as AppLeadsB2bLeadIdRouteImport } from './routes/_app/leads-b2b/$leadId'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LoginRoute,
} as any)
const AppRotasInteligentesRoute = AppRotasInteligentesRouteImport.update({
  id: '/rotas-inteligentes',
  path: '/rotas-inteligentes',
  getParentRoute: () => AppRoute,
} as any)
const AppRegioesPrioritariasRoute = AppRegioesPrioritariasRouteImport.update({
  id: '/regioes-prioritarias',
  path: '/regioes-prioritarias',
  getParentRoute: () => AppRoute,
} as any)
const AppRecomendacoesRoute = AppRecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaOportunidadesRoute = AppMapaOportunidadesRouteImport.update({
  id: '/mapa-oportunidades',
  path: '/mapa-oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaDeCalorRoute = AppMapaDeCalorRouteImport.update({
  id: '/mapa-de-calor',
  path: '/mapa-de-calor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsB2bRoute = AppLeadsB2bRouteImport.update({
  id: '/leads-b2b',
  path: '/leads-b2b',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarCnpjsRoute = AppImportarCnpjsRouteImport.update({
  id: '/importar-cnpjs',
  path: '/importar-cnpjs',
  getParentRoute: () => AppRoute,
} as any)
const AppFunilComercialRoute = AppFunilComercialRouteImport.update({
  id: '/funil-comercial',
  path: '/funil-comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseDeDadosRoute = AppBaseDeDadosRouteImport.update({
  id: '/base-de-dados',
  path: '/base-de-dados',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsB2bLeadIdRoute = AppLeadsB2bLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsB2bRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/base-de-dados': typeof AppBaseDeDadosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/funil-comercial': typeof AppFunilComercialRoute
  '/importar-cnpjs': typeof AppImportarCnpjsRoute
  '/leads-b2b': typeof AppLeadsB2bRouteWithChildren
  '/mapa-de-calor': typeof AppMapaDeCalorRoute
  '/mapa-oportunidades': typeof AppMapaOportunidadesRoute
  '/recomendacoes': typeof AppRecomendacoesRoute
  '/regioes-prioritarias': typeof AppRegioesPrioritariasRoute
  '/rotas-inteligentes': typeof AppRotasInteligentesRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/leads-b2b/$leadId': typeof AppLeadsB2bLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/base-de-dados': typeof AppBaseDeDadosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/funil-comercial': typeof AppFunilComercialRoute
  '/importar-cnpjs': typeof AppImportarCnpjsRoute
  '/leads-b2b': typeof AppLeadsB2bRouteWithChildren
  '/mapa-de-calor': typeof AppMapaDeCalorRoute
  '/mapa-oportunidades': typeof AppMapaOportunidadesRoute
  '/recomendacoes': typeof AppRecomendacoesRoute
  '/regioes-prioritarias': typeof AppRegioesPrioritariasRoute
  '/rotas-inteligentes': typeof AppRotasInteligentesRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/leads-b2b/$leadId': typeof AppLeadsB2bLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/base-de-dados': typeof AppBaseDeDadosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/funil-comercial': typeof AppFunilComercialRoute
  '/_app/importar-cnpjs': typeof AppImportarCnpjsRoute
  '/_app/leads-b2b': typeof AppLeadsB2bRouteWithChildren
  '/_app/mapa-de-calor': typeof AppMapaDeCalorRoute
  '/_app/mapa-oportunidades': typeof AppMapaOportunidadesRoute
  '/_app/recomendacoes': typeof AppRecomendacoesRoute
  '/_app/regioes-prioritarias': typeof AppRegioesPrioritariasRoute
  '/_app/rotas-inteligentes': typeof AppRotasInteligentesRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/_app/leads-b2b/$leadId': typeof AppLeadsB2bLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/base-de-dados'
    | '/configuracoes'
    | '/dashboard'
    | '/funil-comercial'
    | '/importar-cnpjs'
    | '/leads-b2b'
    | '/mapa-de-calor'
    | '/mapa-oportunidades'
    | '/recomendacoes'
    | '/regioes-prioritarias'
    | '/rotas-inteligentes'
    | '/login/reset-password'
    | '/leads-b2b/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/base-de-dados'
    | '/configuracoes'
    | '/dashboard'
    | '/funil-comercial'
    | '/importar-cnpjs'
    | '/leads-b2b'
    | '/mapa-de-calor'
    | '/mapa-oportunidades'
    | '/recomendacoes'
    | '/regioes-prioritarias'
    | '/rotas-inteligentes'
    | '/login/reset-password'
    | '/leads-b2b/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/_app/base-de-dados'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/funil-comercial'
    | '/_app/importar-cnpjs'
    | '/_app/leads-b2b'
    | '/_app/mapa-de-calor'
    | '/_app/mapa-oportunidades'
    | '/_app/recomendacoes'
    | '/_app/regioes-prioritarias'
    | '/_app/rotas-inteligentes'
    | '/login/reset-password'
    | '/_app/leads-b2b/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reset-password': {
      id: '/login/reset-password'
      path: '/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_app/rotas-inteligentes': {
      id: '/_app/rotas-inteligentes'
      path: '/rotas-inteligentes'
      fullPath: '/rotas-inteligentes'
      preLoaderRoute: typeof AppRotasInteligentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regioes-prioritarias': {
      id: '/_app/regioes-prioritarias'
      path: '/regioes-prioritarias'
      fullPath: '/regioes-prioritarias'
      preLoaderRoute: typeof AppRegioesPrioritariasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recomendacoes': {
      id: '/_app/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof AppRecomendacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa-oportunidades': {
      id: '/_app/mapa-oportunidades'
      path: '/mapa-oportunidades'
      fullPath: '/mapa-oportunidades'
      preLoaderRoute: typeof AppMapaOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa-de-calor': {
      id: '/_app/mapa-de-calor'
      path: '/mapa-de-calor'
      fullPath: '/mapa-de-calor'
      preLoaderRoute: typeof AppMapaDeCalorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-b2b': {
      id: '/_app/leads-b2b'
      path: '/leads-b2b'
      fullPath: '/leads-b2b'
      preLoaderRoute: typeof AppLeadsB2bRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-cnpjs': {
      id: '/_app/importar-cnpjs'
      path: '/importar-cnpjs'
      fullPath: '/importar-cnpjs'
      preLoaderRoute: typeof AppImportarCnpjsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funil-comercial': {
      id: '/_app/funil-comercial'
      path: '/funil-comercial'
      fullPath: '/funil-comercial'
      preLoaderRoute: typeof AppFunilComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/base-de-dados': {
      id: '/_app/base-de-dados'
      path: '/base-de-dados'
      fullPath: '/base-de-dados'
      preLoaderRoute: typeof AppBaseDeDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-b2b/$leadId': {
      id: '/_app/leads-b2b/$leadId'
      path: '/$leadId'
      fullPath: '/leads-b2b/$leadId'
      preLoaderRoute: typeof AppLeadsB2bLeadIdRouteImport
      parentRoute: typeof AppLeadsB2bRoute
    }
  }
}

interface AppLeadsB2bRouteChildren {
  AppLeadsB2bLeadIdRoute: typeof AppLeadsB2bLeadIdRoute
}

const AppLeadsB2bRouteChildren: AppLeadsB2bRouteChildren = {
  AppLeadsB2bLeadIdRoute: AppLeadsB2bLeadIdRoute,
}

const AppLeadsB2bRouteWithChildren = AppLeadsB2bRoute._addFileChildren(
  AppLeadsB2bRouteChildren,
)

interface AppRouteChildren {
  AppBaseDeDadosRoute: typeof AppBaseDeDadosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFunilComercialRoute: typeof AppFunilComercialRoute
  AppImportarCnpjsRoute: typeof AppImportarCnpjsRoute
  AppLeadsB2bRoute: typeof AppLeadsB2bRouteWithChildren
  AppMapaDeCalorRoute: typeof AppMapaDeCalorRoute
  AppMapaOportunidadesRoute: typeof AppMapaOportunidadesRoute
  AppRecomendacoesRoute: typeof AppRecomendacoesRoute
  AppRegioesPrioritariasRoute: typeof AppRegioesPrioritariasRoute
  AppRotasInteligentesRoute: typeof AppRotasInteligentesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBaseDeDadosRoute: AppBaseDeDadosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFunilComercialRoute: AppFunilComercialRoute,
  AppImportarCnpjsRoute: AppImportarCnpjsRoute,
  AppLeadsB2bRoute: AppLeadsB2bRouteWithChildren,
  AppMapaDeCalorRoute: AppMapaDeCalorRoute,
  AppMapaOportunidadesRoute: AppMapaOportunidadesRoute,
  AppRecomendacoesRoute: AppRecomendacoesRoute,
  AppRegioesPrioritariasRoute: AppRegioesPrioritariasRoute,
  AppRotasInteligentesRoute: AppRotasInteligentesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginResetPasswordRoute: LoginResetPasswordRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
